/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSkillsRouteImport } from './routes/_site.skills'
import { Route as SiteServicesRouteImport } from './routes/_site.services'
import { Route as SiteResumeRouteImport } from './routes/_site.resume'
import { Route as SiteProjectsRouteImport } from './routes/_site.projects'
import { Route as SiteCertificatesRouteImport } from './routes/_site.certificates'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSkillsRoute = SiteSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SiteResumeRoute = SiteResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsRoute = SiteProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCertificatesRoute = SiteCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/certificates': typeof SiteCertificatesRoute
  '/projects': typeof SiteProjectsRoute
  '/resume': typeof SiteResumeRoute
  '/services': typeof SiteServicesRoute
  '/skills': typeof SiteSkillsRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/certificates': typeof SiteCertificatesRoute
  '/projects': typeof SiteProjectsRoute
  '/resume': typeof SiteResumeRoute
  '/services': typeof SiteServicesRoute
  '/skills': typeof SiteSkillsRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/certificates': typeof SiteCertificatesRoute
  '/_site/projects': typeof SiteProjectsRoute
  '/_site/resume': typeof SiteResumeRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/skills': typeof SiteSkillsRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/certificates'
    | '/projects'
    | '/resume'
    | '/services'
    | '/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/certificates'
    | '/projects'
    | '/resume'
    | '/services'
    | '/skills'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/certificates'
    | '/_site/projects'
    | '/_site/resume'
    | '/_site/services'
    | '/_site/skills'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/skills': {
      id: '/_site/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SiteSkillsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/resume': {
      id: '/_site/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof SiteResumeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects': {
      id: '/_site/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof SiteProjectsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/certificates': {
      id: '/_site/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof SiteCertificatesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteCertificatesRoute: typeof SiteCertificatesRoute
  SiteProjectsRoute: typeof SiteProjectsRoute
  SiteResumeRoute: typeof SiteResumeRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteSkillsRoute: typeof SiteSkillsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteCertificatesRoute: SiteCertificatesRoute,
  SiteProjectsRoute: SiteProjectsRoute,
  SiteResumeRoute: SiteResumeRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteSkillsRoute: SiteSkillsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
